### ISSUE TITLE
Template html seems broken

### ISSUE THREAD

**Issue by Mr-Ples** [yoheinakajima/instagraph#1]
i get this instead of a graph
![image](https://github.com/yoheinakajima/instagraph/assets/27857264/2c20b023-0465-4ef7-9e78-44e8a6b81e19)

looking at the index.html it seems rekt (some text meant to be in script tags are just hanging out below the html closing tag

**Comment by Lukafin** [comment]
Made PR for this:
https://github.com/yoheinakajima/instagraph/pull/2

**Comment by yoheinakajima** [comment]
thx @Lukafin!
