### ISSUE TITLE
[Feature] Docker file is missing 

### ISSUE THREAD

**Issue by prasantpoudel** [yoheinakajima/instagraph#16]
Many prefer to run the code on docker so they didn't require to manually install the requirements.

Assign me I will complete.

**Comment by jinnabaalu** [comment]
I have added the configuration required for the Dockerisation. [PR #17](https://github.com/yoheinakajima/instagraph/pull/17)
Hope @yoheinakajima  accepts this.

**Comment by yoheinakajima** [comment]
Huh I need to learn GitHub. Didn't even know I could assign.

Is there an AI agent that manages GitHub for you? 🙃

**Comment by mahimairaja** [comment]
> Huh I need to learn GitHub. Didn't even know I could assign.
>
> Is there an AI agent that manages GitHub for you? 🙃

Ofcourse, you can use Github Actions to handle it for you!

**Comment by mahimairaja** [comment]
Is anyone working on this? To make a dockerfile or image itself? If not let me know please... I would like to contribute
