### ISSUE TITLE
Graph

### ISSUE THREAD

**Issue by rarhs** [yoheinakajima/instagraph#20]
console has been displaying the following - `127.0.0.1 - - [16/Sep/2023 11:04:40] "POST /get_response_data HTTP/1.1" 200` but the graph is not being displayed at http://127.0.0.1:8080

**Comment by crsrusl** [comment]
Yup, I've tried in multiple browsers it doesn't draw the graph.

**Comment by ateliershen** [comment]
I am encountering this issue as well. Most of the time it throws the following exception:
`Fetch Error: SyntaxError: JSON.parse: expected double-quoted property name at line <x> column <y> of the JSON data`

But very occasionally it returns the graph correctly.

**Comment by shepherd-06** [comment]
Resolved on https://github.com/yoheinakajima/instagraph/pull/26.
