### ISSUE TITLE
Free users go beyond rate limits

### ISSUE THREAD

**Issue by Meithal** [yoheinakajima/instagraph#21]
Free users can only do 3 requests per minute, by default when submitting a request the app doesn't wait and the quote is exceeded, and a stack trace is shown on the console launching the flask app.

A solution for free users would be to wait 20 or 30 seconds between each request towards openai api.

**Comment by prasantpoudel** [comment]
Thank you for feedback, Working on the problem..

**Comment by Saswatsusmoy** [comment]
Can I give it an attempt to work on this issue now?

**Comment by Saswatsusmoy** [comment]
![code](https://github.com/yoheinakajima/instagraph/assets/72549122/d8def2c3-d588-4a9c-8785-a18106685035)


@Meithal will this code work as I have tried to add a rate limiter while delaying the user for 20 seconds

**Comment by prasantpoudel** [comment]
Check it locally if it's work than file PR.

**Comment by berkantay** [comment]
Having the same issue here, great to see a [PR](https://github.com/yoheinakajima/instagraph/pull/27) has created.
