### ISSUE TITLE
[BUG] Not generating graphs from URL

### ISSUE THREAD

**Issue by tobiasgadsby** [yoheinakajima/instagraph#36]
**Describe the bug**
Generates graphs from a text prompt but no graph is generated from a URL input.

**To Reproduce**
1. Clone the repository.
2. Install the requirements.
3. Prepare the environment by adding your Openai key and changing the name of the env file to .env.
4. Run main.py.
4. Open localhost and enter a URL (e.g. https://aws.amazon.com/what-is/quantum-computing/)
5. Wait for the loading bar to finish, no graph is generated

**Expected behaviour**
Generation of a graph from the URL.

**Screenshots**
<img width="1349" alt="Screenshot 2023-09-17 at 18 05 31" src="https://github.com/yoheinakajima/instagraph/assets/133044093/8478c0f8-6e19-4b54-b1e8-1bb9e1b39b74">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser firefox
 - Version [Latest]

**Comment by danryland** [comment]
Hey @Asheqer,

I tried this in latest Firefox, MacOS and it worked as expected (see screenshot)

Two follow-up questions:
- Does your terminal give any clues as to a potential 500 error or something similar?
- Does the browser console log give any clues? (I have noticed there there are occasional warnings regarding style properties and mappings)
- Do normal, non-URL questions work to make sure your Open API key is working correctly? 

<img width="1737" alt="Screenshot 2023-09-18 at 12 42 14" src="https://github.com/yoheinakajima/instagraph/assets/4310937/24b10489-2ffd-4d85-ad99-8787957111b7">

**Comment by Tayyab-R** [comment]
Hey @Asheqer 
I tried the same as you described you in your issue in Microsoft Edge, Ubuntu and it worked as expected.

- **If you are not getting error messages in your terminal that @danryland said, then you should give a try pulling the repo again.**

Hope this solves the issue.

![3](https://github.com/yoheinakajima/instagraph/assets/59740422/4ff48e6d-493d-41ac-a49b-e65dc09ed5e8)
