### ISSUE TITLE
problem installing the requirement neo4j , i keep getting this error

### ISSUE THREAD

**Issue by Agarshanan-Kasithasan** [yoheinakajima/instagraph#6]
Collecting neo4j==5.12.0
  Downloading neo4j-5.12.0.tar.gz (190 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.9/190.9 KB 2.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Generating metadata for package neo4j produced metadata for project name unknown. Fix your #egg=neo4j fragments.
Discarding https://files.pythonhosted.org/packages/19/11/9af80c8621ba433039bf47acd7b037998138516eb86fdb9ba492c49ee844/neo4j-5.12.0.tar.gz#sha256=00a776a687267150f9e1950017316b751cf63db7b734a699b1405ac20fd4a731 (from https://pypi.org/simple/neo4j/) (requires-python:>=3.7): Requested unknown from https://files.pythonhosted.org/packages/19/11/9af80c8621ba433039bf47acd7b037998138516eb86fdb9ba492c49ee844/neo4j-5.12.0.tar.gz#sha256=00a776a687267150f9e1950017316b751cf63db7b734a699b1405ac20fd4a731 (from -r requirements.txt (line 6)) has inconsistent name: filename has 'neo4j', but metadata has 'unknown'
ERROR: Could not find a version that satisfies the requirement neo4j==5.12.0 (from versions: 1.7.0b1, 1.7.0b2, 1.7.0b3, 1.7.0b4, 1.7.0rc1, 1.7.0rc2, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 4.0.0a1, 4.0.0a2, 4.0.0a3, 4.0.0a4, 4.0.0b1, 4.0.0b2, 4.0.0rc1, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.1.0rc1, 4.1.0rc2, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.2.0a1, 4.2.0, 4.2.1, 4.3.0a1, 4.3.0b1, 4.3.0rc1, 4.3.0, 4.3.1, 4.3.2, 4.3.3, 4.3.4, 4.3.5, 4.3.6, 4.3.7, 4.3.8, 4.3.9, 4.4.0a1, 4.4.0b1, 4.4.0, 4.4.1, 4.4.2, 4.4.3, 4.4.4, 4.4.5, 4.4.6, 4.4.7, 4.4.8, 4.4.9, 4.4.10, 4.4.11, 5.0.0a1, 5.0.0a2, 5.0.0, 5.0.1, 5.1.0, 5.2.0, 5.2.1, 5.3.0, 5.4.0, 5.5.0, 5.6.0, 5.7.0, 5.8.0, 5.8.1, 5.9.0, 5.10.0, 5.11.0, 5.12.0)
ERROR: No matching distribution found for neo4j==5.12.0

**Comment by srividhyaprakash** [comment]
I faced this error too.

Simply type `pip install neo4j` from the terminal and it should automatically find the lowest neo4j version that's compatible with your Linux distribution and install it for you.

Comment the line in `requirements.txt` that mentions `neo4j` and run `pip install -r requirements.txt`.


On the other hand, you could try upgrading your python version to >=3.7
